### ISSUE TITLE
example config typo

### ISSUE THREAD

**Issue by akeeler** [pixie16/pixie_scan#22]
there is a typo in line 60 of the example.xml file

It currently reads `<Process name=...>`
It should read `<Processor name=...>`

**Comment by ksmith0** [comment]
Could you put the code in a code block denoted by single or triple back ticks? The comment block disappears in my email and on the website.

Markdown info:
https://help.github.com/articles/basic-writing-and-formatting-syntax/

**Comment by akeeler** [comment]
fixed the comment

**Comment by ksmith0** [comment]
Thanks.
