### ISSUE TITLE
Trace Seg Fault.

### ISSUE THREAD

**Issue by ksmith0** [pixie16/pixie_scan#24]
If the trace settings are incorrectly set a segmentation fault can occur. The reason behind this is that the `low` value is not checked against the size of the trace and the following line from src/core/Trace.cpp line 99
`Trace::const_iterator itTrace = max_element(begin()+low, end()-(size()-high));`
may start larger than the trace. The following check `if (size() < low)` would resolve this issue. There may need to be additional checks here to avoid a segfault as well. A check for high already exists and these could be combined.

**Comment by spaulaus** [comment]
The root cause of this issue was a XML file that was setup for a different version of the software. The low variable was set to the ULONG_MAX, since it was never initialized properly.

**Comment by ksmith0** [comment]
I don't think this was fixed. You can still have seg faults which leave the user confused instead of providing some useful message about a possible problem. We should cat h errors where we can.

**Comment by spaulaus** [comment]
It was fixed in utkscan. I agree about the error messages, but disagree about fixing code that is an unsupported fork.

**Comment by ksmith0** [comment]
Unfortunately I think we still need to support this fork with the hollifiekd libraries until a true online mode is completely supported in pass.

**Comment by spaulaus** [comment]
The fork that is being worked with at TTU is not the main software branch, but a forked version that hacked in SHM with poll2. The work involved with bringing that branch up to the main is significant.

**Comment by spaulaus** [comment]
The specific error that you are referring to from the TTU version *is* fixed in the main branch, because if it cannot find values for the missing parameters, it assumes default ones. This will prohibits that error from occurring.

**Comment by ksmith0** [comment]
Does the master on here have the same issue? I don't want to support hacked code, but I believe this repo pixie_scan still needs support. Pass is not 100% for an experiment at this point as we have seen at ND and ISOLDE.

**Comment by spaulaus** [comment]
See the above comment, default values are assumed, preventing the error.

**Comment by spaulaus** [comment]
[This](https://github.com/pixie16/pixie_scan/blob/24d5cff34a5700b133edb369bcc203c2829dbc67/include/Globals.hpp#L214) function in the main branch mitigates the error that you describe.
