### ISSUE TITLE
 Differences in .ldf to .his as compared to MCA.his

### ISSUE THREAD

**Issue by scshadrick** [pixie16/pixie_scan#25]
The pixie scan code produced a histogram that is roughly halved in amplitude and double the length in bins.  There may be a binning issue in pixie scan or a compression issue in PixieSuite2.

The above his was from the ldf scan, the bottom was from MCA.his.  Note otherwise similar characteristics. 
![comparison_cs137_mca_scan2](https://cloud.githubusercontent.com/assets/20971746/17591295/2ea0993e-5fa3-11e6-816e-747b74ee9c95.png)

**Comment by ksmith0** [comment]
@spaulaus Is this a data compression factor for damm? or an issue with the MCA scale?

**Comment by spaulaus** [comment]
The MCA has a binning factor. This is discussed in section 3.3.3 of the Pixie-16 User's Manual v. 1.40. This is normal behavior.
