### ISSUE TITLE
Doxygen documentation is empty.

### ISSUE THREAD

**Issue by ksmith0** [pixie16/pixie_scan#4]
After doxygen compilation in the doc folder:
$ doxygen Doxyfile 
The resulting html documentation is empty. The basic html structure is there, but no classes / files are documented.
Using doxygen 1.8.9.1.

Output of doxygen:
    Warning: tag INPUT: input source `include' does not exist
    Warning: tag INPUT: input source `src' does not exist
    Warning: tag INPUT: input source `doc/doxyPages' does not exist
    warning: source src is not a readable file or directory... skipping.
    warning: source include is not a readable file or directory... skipping.
    warning: source doc/doxyPages is not a readable file or directory... skipping.
    warning: source include is not a readable file or directory... skipping.
    warning: source src is not a readable file or directory... skipping.
    warning: source doc/doxyPages is not a readable file or directory... skipping.
    ...

Looks like the Doxyfile is not configured to look in the correct folder for the source and include files.

**Comment by spaulaus** [comment]
Did you try the "make doc" recipe in the base directory? The Doxyfile is setup for paths relative to the base directory. 

Both commands: "make doc" and "doxygen doc/Doxyfile" (from the base directory); should be equivalent.

**Comment by ksmith0** [comment]
You are correct, I had attempted to run `doxygen Doxyfile` directly from the doc directory.
