### ISSUE TITLE
Fitting doesn't work properly for SiPM fast signals

### ISSUE THREAD

**Issue by sztaylor89** [pixie16/pixie_scan#9]
![beta_timing_merge](https://cloud.githubusercontent.com/assets/4438375/14823112/5b015fa2-0b9f-11e6-8ba4-502998d67935.png)

Results after merging my code with the master branch.  The sipm timing signals showed some periodic peaks before the merge, but it is now much worse.  I scanned over a135feb_12.ldf from the ANL2015 data using an updated config file(see attached).

[Config.txt](https://github.com/pixie16/pixie_scan/files/236902/Config.txt)

**Comment by spaulaus** [comment]
This is a problem with which parameter you have defined for the SiPM timing function. It uses Gamma, and not Beta.
